apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-frame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-frame
  template:
    metadata:
      labels:
        app: get-frame
    spec:
      containers:
        - name: get-frame
          image: avherrera/get-frame:v0.0.3
          ports:
            - containerPort: 5003
          volumeMounts:
            - name: video-storage
              mountPath: /app/data # El contenedor accederá a /app/data
      volumes:
        - name: video-storage
          persistentVolumeClaim:
            claimName: nfs-pvc # El PVC que usaremos para almacenar los videos
