apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-video
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload-video
  template:
    metadata:
      labels:
        app: upload-video
    spec:
      containers:
        - name: upload-video
          image: avherrera/upload-video:v0.0.2
          ports:
            - containerPort: 5002
          volumeMounts:
            - name: video-storage
              mountPath: /app/data # El contenedor accederá a /app/data
      volumes:
        - name: video-storage
          persistentVolumeClaim:
            claimName: nfs-pvc # El PVC que usaremos para almacenar los videos
