apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-detection
  template:
    metadata:
      labels:
        app: server-detection
    spec:
      containers:
        - name: server-detection
          image: avherrera/server-detection:v0.0.1
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: video-storage
              mountPath: /app/videos # El contenedor accederá a /app/videos
      volumes:
        - name: video-storage
          persistentVolumeClaim:
            claimName: video-pvc # El PVC que usaremos para almacenar los videos


          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "200m"
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
