apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-detection
  template:
    metadata:
      labels:
        app: server-detection
    spec:
      containers:
        - name: server-detection
          image: avherrera/server-detection:v0.1.1
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "3000m"
              memory: "2Gi"
            limits:
              cpu: "4000m"
              memory: "4Gi"
          volumeMounts:
            - name: video-storage
              mountPath: /app/data # El contenedor accederá a /app/data
      volumes:
        - name: video-storage
          persistentVolumeClaim:
            claimName: nfs-pvc # El PVC que usaremos para almacenar los videos
