apiVersion: v1
kind: Service
metadata:
  name: get-frame
  annotations:
  labels:
    app: get-frame
spec:
  type: ClusterIp
  selector:
    app: get-frame
  ports:
    - name: http
      protocol: TCP
      port: 5003
      targetPort: 5003
