apiVersion: v1
kind: Service
metadata:
  name: server-detection
spec:
  selector:
    app: server-detection
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000  # container
    # nodePort: 30035
    protocol: TCP