apiVersion: v1
kind: Service
metadata:
  name: server-detection
  annotations:
  labels:
    app: server-detection
spec:
  type: LoadBalancer
  selector:
    app: server-detection
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
