# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: video-storage-pv
# spec:
#   capacity:
#     storage: 10Gi  # Define el tamaño del volumen
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: /app/videos  # Reemplaza con la ruta a tus videos en el nodo del clúster
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-pvc
spec:
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi  # Debe coincidir con el tamaño del PV
  storageClassName: do-block-storage
